# Dependencies for ROxygen ####

#' @importFrom R6 R6Class
#' @useDynLib metabc


# R6 Class CMetabDo ####

#' @export
#'
#' @title
#'   Time series DO metabolism model based on C++ implementation
#'
#' @description
#'   Predicts the change in dissolved oxygen in an aquatic system
#'   over time due to metabolic processes and gas exchange with the
#'   atmosphere.
#'
#'   Implementation of this model is provided by C++ objects.
#'
CMetabDo <- R6Class(
   classname = "CMetabDo",
   inherit = CMetab,
   public = list(

      ## Attributes ####

      #' @field type
      #'   A character string indicating type of solution used.
      #'   (e.g. "ForwardEuler" or "CrankNicolson" are known solutions)
      type = NULL,

      #' @field timePOSIX
      #'   A vector of POSIXct type time objects representing the
      #'   times at which DO concentrations are simulated
      timePOSIX = NULL,

      #' @field output
      #'   The output generated when the model is run.
      #'   This is a list of dataframes with the following named elements.
      #'   \itemize{
      #'     \item base:
      #'       fundamental model output data frame with the following columns
      #'       \itemize{
      #'         \item dt:
      #'           the duration of each time step (days)
      #'         \item cFixation:
      #'           the number of atoms of carbon fixed during the
      #'           time step (micromoles per liter)
      #'         \item cRespiration:
      #'           the number of atoms of carbon respired during the
      #'           time step (micromoles per liter)
      #'       }
      #'     \item do:
      #'       model output associated with dissolved oxygen calculations,
      #'       a data frame with the following elements
      #'       \itemize{
      #'         \item dox:
      #'           the concentration of dioxygen gas at the beginning of
      #'           the time step (micromolarity)
      #'         \item doSat:
      #'           the saturation concentration of dioxygen gas at the
      #'           beginning of the time step (micromolarity)
      #'         \item doProduction:
      #'           the number of dioxygen gas molecules generated by
      #'           primary production during the time step per volume of water
      #'           (micromolarity)
      #'         \item doConsumption:
      #'           the number of dioxygen gas molecules consumed by
      #'           respiration during the time step per volume of water
      #'           (micromolarity)
      #'         \item k:
      #'           the gas exchange rate for oxygen used during the time step
      #'           (per day)
      #'         \item doEquilibration:
      #'           the net number of dissolved carbon dioxide gas molecules exchanged
      #'           with the atomosphere during the time step per volume of water
      #'           (micromolarity)
      #'       }
      #'   }
      output = NULL,

      ## Method: constructor ####

      #' @description
      #'   Constructs an object that is a new instance of the class
      #'
      #' @param type
      #'    A character string indicating type of solution used.
      #'    (e.g. "ForwardEuler" or "CrankNicolson" are known solutions)
      #' @param dailyGPP
      #'    Model parameter for daily gross primary production
      #'    based on an effective concentration of DOC fixed.
      #'    Units of micromoles per liter per day.
      #' @param ratioDoCFix
      #'    Ratio of DO molecules produced relative to carbon atoms fixed.
      #'    Defaults to 1.
      #' @param dailyER
      #'    Model parameter for daily aerobic ecosystem respiration
      #'    based on an effective concentration of DOC respired
      #'    Units of micromoles per liter per day.
      #' @param ratioDoCResp
      #'    Ratio of DO molecules consumed relative to carbon atoms respired.
      #'    Defaults to -1.
      #' @param k600
      #'    Influence of atmospheric gas exchange on oxygen concentration
      #'    as a first-order rate depending on saturation deficit.
      #'    Units are per day.
      #' @param initialDO
      #'    Initial DO concentration at the beginning of the evaluation period.
      #'    Units are micromoles per liter per day.
      #' @param time
      #'    Vector of times at which DO will be predicted.
      #'    These times must align with vectors provided for temperature and
      #'    photosynthetically active radiation.
      #'    Type should be a POSIXct vector or character vector that can be forced
      #'    to a POSIXct by default (e.g. format of "YYYY-MM-DD HH:mm:ss").
      #' @param temp
      #'    Vector of water temperatures in degrees Celsius.
      #'    Must be same length as the time vector.
      #' @param par
      #'    Vector of photosynthetically active radiation values.
      #'    Units are arbitrary if linear with PAR intensity, but must be consistent
      #'    with total PAR if the optional argument for total PAR is specified.
      #'    Must be the same length as the time vector.
      #' @param parTotal
      #'    Total PAR for period of analysis, see units note in par argument description.
      #'    If a negative value is provided, the model will integrate the par data
      #'    provided to estimate the total PAR.
      #'    Defaults to -1.
      #' @param airPressure
      #'    Barometric pressure.
      #'    Units must be consistent with the units of the optional standard air pressure
      #'    argument.
      #'    If default stdAirPressure is used, this should be a fraction of the standard
      #'    air pressure at sea level.
      #' @param stdAirPressure
      #'    The standard air pressure in the desired units.
      #'    Defaults to 1 standard atmosphere.
      #' @param gwAlpha
      #'    The turnover rate of channel water due to groundwater input.
      #'    Units of per day.
      #'    Default value is NA, which disables groundwater inflow simulation.
      #'    Can be a single value or a vector that provides a changing value over time.
      #' @param gwDO
      #'    The concentration of DO in inflowing groundwater.
      #'    Units of micromolarity.
      #'    Default value is NA, which disables groundwater inflow simulation.
      #'    Can be a single value or a vector that provides a changing value over time.
      #'
      initialize = function
      (
         type = "ForwardEuler",
         dailyGPP,
         ratioDoCFix = 1,
         dailyER,
         ratioDoCResp = -1,
         k600,
         initialDO,
         time,
         temp,
         par,
         parTotal = -1,
         airPressure,
         stdAirPressure = 1,
         gwAlpha = NA,
         gwDO = NA
      )
      {
         self$type <- type;
         self$timePOSIX <- as.POSIXct(time);
         time <- as.numeric(time) / 86400;
         airPressure <- rep(0, length(time)) + airPressure;

         self$pointers <- .Call(
            sprintf("Metab%sDo_constructor", self$type)
         );

         gwDOEnable = !(anyNA(gwAlpha) || anyNA(gwDO));
         if (gwDOEnable) {
            gwAlpha <- rep(0, length(time)) + gwAlpha;
            gwDO <- rep(0, length(time)) + gwDO;
         }

         .Call(
            "MetabDo_initialize",
            self$pointers$baseExternalPointer,
            dailyGPP,
            ratioDoCFix,
            dailyER,
            ratioDoCResp,
            k600,
            initialDO,
            time,
            temp,
            par,
            parTotal,
            airPressure,
            stdAirPressure,
            gwDOEnable,
            gwAlpha,
            gwDO
         )
      },

      ## Method: destructor ####

      #' @description
      #'   Calls the R wrapper of the destructor of the
      #'   underlying C object to release memory.
      #'   Do not call this manually unless you really know what you are doing.
      #'
      #' @return
      #'   SEXP object returned by the destructor method
      #'
      finalize = function()
      {
         .Call(
            sprintf("Metab%sDo_destructor", self$type),
            self$pointers$modelExternalPointer
         )
      },

      ## Method: run ####

      #' @description
      #'   Runs a simulation based on parameters and driving data
      #'   in the object attributes. Output will be stored in the
      #'   output attribute, but is also returned from this function
      #'   as a convenience.
      #'
      #' @return
      #'   A named list of dataframes containing model output. See description
      #'   of the output attribute for details.
      #'
      run = function()
      {
         super$run();
         results <- .Call(
            "MetabDo_getSummary",
            self$pointers$baseExternalPointer
         )
         self$output <- list(
            base = data.frame(results$output),
            do = data.frame(results$outputDo)
         );
         return(self$output);
      },

      ## Method: setMetabDoParam ####

      #' @description
      #'   Sets one of the DO related model parameters to a new value.
      #'
      #' @param param
      #'   A character string to indicate the parameter to be changed
      #'   \itemize{
      #'     \item "RatioDoCFix": change the C fixation stoichiometric parameter
      #'     \item "RatioDoCResp": change the C respiration stoichiometric parameter
      #'   }
      #' @param value
      #'   The new value for the parameter
      #'
      #' @return
      #'   The previous value of the parameter
      #'
      setMetabDoParam = function(param, value)
      {
         .Call(
            sprintf("MetabDo_set%s", param),
            self$pointers$baseExternalPointer,
            value
         )
      }

   )
)
